services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=replace_this_with_a_secure_random_string_in_production

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - WDS_SOCKET_PORT=0
